// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbcvzomqaowoumuzyjly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iY3Z6b21xYW93b3VtdXp5amx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTYyNzYsImV4cCI6MjA3NzMzMjI3Nn0.kj9YdUAZFgxrq0H6JG5_r4S9RqjI1W6u34QjTRPe_5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});